**1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**


**Ans**. NumPy enhances Python's capabilities for numerical operations by providing fast, efficient array processing, supporting large multi-dimensional arrays and matrices, and offering a wide range of mathematical functions. Its purpose is to enable high-performance scientific computing and data analysis by optimizing operations using vectorization, which avoids Python loops and leverages optimized C code for speed. This makes numerical computations significantly faster and more memory-efficient than using Python's built-in data structures.

**2.Compare and contrast np.mean()and np.average()functions in NumPy. When would you use one over the other?**

**Ans.**np.mean() calculates the simple arithmetic mean of array elements without considering weights, making it suitable for straightforward average calculations. In contrast, np.average() can compute a weighted average, where each element can have a different level of influence. Use np.mean() for basic averaging needs and np.average()when you need to account for weights in your data.

**3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

**Ans.**To reverse a NumPy array, you can use slicing or the np.flip() function:
1D Array: You can reverse a 1D array using slicing:

In [1]:
import numpy as np # import the numpy library and alias it as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # Output: [5, 4, 3, 2, 1]
print(reversed_arr)

[5 4 3 2 1]


In [2]:
#2D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr = arr[::-1, ::-1]  # Output: [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
print(reversed_arr)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


**4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**


**Ans.**You can determine the data type of elements in a NumPy array using the .dtype attribute:

**5. Define ndarrays in NumPy and explain their key features. How do they
differ from standard Python lists?**

**Ans.**ndarrays in NumPy are multi-dimensional arrays that store elements of the same data type in a contiguous block of memory. Key features include support for high-performance vectorized operations, built-in mathematical functions, and efficient slicing and indexing.

Compared to standard Python lists, ndarrays offer:
Faster computation: They use optimized C code under the hood.
Lower memory usage: They store data more compactly.

**6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations**

**Ans.**NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations. This is because NumPy arrays use contiguous blocks of memory and are implemented in C, enabling them to perform vectorized operations without the need for Python loops. This results in faster execution and more efficient memory usage.

For large datasets, NumPy's operations are highly optimized, often running orders of magnitude faster than equivalent operations with Python lists. Additionally, arrays have built-in functions for complex computations, which further speeds up processing compared to iterating manually with lists. This makes NumPy a powerful tool for handling large-scale numerical tasks efficiently.

**7.Compare vstack() and hstack()functions in NumPy. Provide examples demonstrating their usage and output.**
**Ans**vstack() and hstack() in NumPy are used to stack arrays together vertically and horizontally, respectively:
vstack(): Stacks arrays vertically (row-wise).

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [4]:
#hstack(): Stacks arrays horizontally (column-wise).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)

[1 2 3 4 5 6]


**8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions**

**Ans.**fliplr() and flipud() in NumPy are used to flip arrays along different axes:
fliplr(): Flips an array left to right (horizontally). It affects the columns of a 2D array by reversing their order.

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)

[[3 2 1]
 [6 5 4]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.flipud(arr)
print(result)

[[4 5 6]
 [1 2 3]]


**9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

**Ans**The array_split()method in NumPy splits an array into specified sub-arrays. Unlike split(),it can handle cases where the array can't be split evenly. If the array's length doesn't divide evenly by the number of splits, array_split()ensures that sub-arrays will vary slightly in size, with some being larger than others.

In [7]:
arr = np.array([1, 2, 3, 4, 5])
splits = np.array_split(arr, 3)
print(splits)

[array([1, 2]), array([3, 4]), array([5])]


**10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?**

**Ans**Vectorization and broadcasting in NumPy are techniques that make array operations faster and more efficient by reducing the need for explicit loops.
Vectorization allows you to perform operations on entire arrays at once, rather than looping through individual elements. This leverages optimized, low-level code, often written in C, making it much faster than traditional Python loops.
Broadcasting enables NumPy to handle arrays of different shapes in operations. For example, you can add a 1D array to a 2D array without explicitly reshaping. NumPy automatically “stretches” the smaller array along the necessary dimensions, allowing operations on mismatched shapes without additional memory overhead.

**Practical Questions:**

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns**

**Ans.**First, create a 3x3 NumPy array with random integers between 1 and 100:


In [8]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

Original Array:
[[61 88 64]
 [75 63 82]
 [22 23 83]]


In [10]:
transposed_array = array.T
print("Transposed Array:")
print(transposed_array)

Transposed Array:
[[61 75 22]
 [88 63 23]
 [64 82 83]]


**2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

**Ans**First, create a 1D NumPy array with 10 elements:


In [12]:

import numpy as np
array = np.arange(10)
print("Original 1D Array:")
print(array)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]


In [13]:
#Reshape it into a 2x5 array:
array_2x5 = array.reshape(2, 5)
print("2x5 Array:")
print(array_2x5)

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
#Then reshape it into a 5x2 array:
array_5x2 = array.reshape(5, 2)
print("5x2 Array:")
print(array_5x2)

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**



In [ ]:
#First, create a 4x4 array with random float values:
import numpy as np
array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array)

In [17]:
#Add a border of zeros around it, resulting in a 6x6 array:

bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Border of Zeros:")
print(bordered_array)
#The np.pad function adds a border of zeros with a width of 1 around the original array.

6x6 Array with Border of Zeros:
[ 0 10 15 20 25 30 35 40 45 50 55 60  0]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5**


In [16]:
import numpy as np
array = np.arange(10, 65, 5)
print(array)
#This will generate an array: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60] where each element increases by 5.

[10 15 20 25 30 35 40 45 50 55 60]


**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.**


In [18]:
#Here’s how you can do it using NumPy:

import numpy as np

# Create the array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

print("Original Array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)

Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array**

In [21]:
import numpy as np
words = np.array(['python', 'numpy', 'pandas'])
#Use np.char.join to insert a space between each character in each word:
print(np.char.join(' ', words))

['p y t h o n' 'n u m p y' 'p a n d a s']


**7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

**Ans**

In [22]:
import numpy as np
words = np.array(['python', 'numpy', 'pandas'])
print("Original Array:", words)
spaced_words = np.char.join(' ', words)
print("Spaced Array:", spaced_words)

Original Array: ['python' 'numpy' 'pandas']
Spaced Array: ['p y t h o n' 'n u m p y' 'p a n d a s']


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**
**Ans**

In [23]:
import numpy as np
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)

Diagonal Elements:
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

**Ans**

In [25]:
import numpy as np
array = np.random.randint(0, 1000, 100)
print("Array of 100 Random Integers:")
print(array)

Array of 100 Random Integers:
[124 818 231 294 600 770 676 167 742 726 587   5 452 149 441 603  97 342
 196 229 598 276  72 785 460 947 864  26 658 163 142 787 709 354 957 217
 929 308 355 902 430 601 675 293 394 871 677 834 696 879 735 804 496 342
 919 752 182 556 925 878 227 734  31 464 238 366  22 771  49 349 412 171
 561 805 929 572 800 256 440 507 414 666 357 809 186 866 325 595 745   0
 849  61 360 926 581 882 657 246 537 261]


In [26]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
    print("Prime Numbers:")
prime_numbers = [num for num in array if is_prime(num)]
print(prime_numbers)

[167, 587, 5, 149, 97, 229, 947, 163, 787, 709, 929, 601, 293, 677, 919, 227, 31, 349, 929, 809, 61]


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**


**Ans**

In [27]:
import numpy as np
# Example temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.randint(20, 36, size=30)
print("Daily Temperatures for a Month:")
print(daily_temperatures)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # Only take the first 28 days for full weeks
print("\nTemperatures Reshaped into Weeks:")
print(weekly_temperatures)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # Only take the first 28 days for full weeks
print("\nTemperatures Reshaped into Weeks:")
print(weekly_temperatures)

Daily Temperatures for a Month:
[25 21 32 28 23 31 30 22 24 26 29 32 24 22 26 35 29 31 33 27 29 20 28 20
 25 29 20 20 21 22]

Temperatures Reshaped into Weeks:
[[25 21 32 28 23 31 30]
 [22 24 26 29 32 24 22]
 [26 35 29 31 33 27 29]
 [20 28 20 25 29 20 20]]

Temperatures Reshaped into Weeks:
[[25 21 32 28 23 31 30]
 [22 24 26 29 32 24 22]
 [26 35 29 31 33 27 29]
 [20 28 20 25 29 20 20]]
